import datetime

topics = [
    'gun control'
]

newsSources = [
    'cnn',
    'FoxNews',
    # 'washtimes',
    # 'wsj',
    # 'usnews',
    # 'latimes',
    # 'usatoday',
    # 'gma'
]



finalTweets = {'gun control': {'FoxNews': [{'content': '',
                                            'link': u'http://fxn.ws/1RlVJD',
                                            'source': 'FoxNews',
                                            'title': '',
                                            'topic': 'gun control',
                                            'twitter': {'body': u'Hollywood stars follow Obamas gun control script, tweeting White House talking points on cue http://fxn.ws/1RlVJDF',
                                                        'date': datetime.datetime(2016, 1, 13, 20, 6, 4),
                                                        'favs': 98,
                                                        'hashtags': '',
                                                        'id': '687485807448297472',
                                                        'link': 'https://twitter.com/FoxNews/status/687485807448297472',
                                                        'mentions': '',
                                                        'retweets': 71}},
                                           {'content': '',
                                            'link': u'https://amp.twimg.com/v/3c4cfb5f-6a8',
                                            'source': 'FoxNews',
                                            'title': '',
                                            'topic': 'gun control',
                                            'twitter': {'body': u'. @RealDonaldTrump on gun control : The guns don\'t pull the trigger. It\'s the people that pull the trigger." https://amp.twimg.com/v/3c4cfb5f-6a8 9-4202-bf3d-e5aa8aecc755 ',
                                                        'date': datetime.datetime(2016, 1, 14, 19, 6, 52),
                                                        'favs': 1297,
                                                        'hashtags': '',
                                                        'id': '687833298760945664',
                                                        'link': 'https://twitter.com/FoxNews/status/687833298760945664',
                                                        'mentions': u'@RealDonaldTrump',
                                                        'retweets': 655}},
                                           {'content': '',
                                            'link': 'http://bit.ly/1QkUmEA',
                                            'source': 'FoxNews',
                                            'title': '',
                                            'topic': 'gun control',
                                            'twitter': {'body': 'Kurt Russell put gun control activists on blast during a recent interview. http://bit.ly/1QkUmEA pic.twitter.com/o706YV7IEq',
                                                        'date': datetime.datetime(2015, 12, 12, 8, 3, 24),
                                                        'favs': 2023,
                                                        'hashtags': '',
                                                        'id': '675707533076660225',
                                                        'link': 'https://twitter.com/FoxNews/status/675707533076660225',
                                                        'mentions': '',
                                                        'retweets': 1130}},
                                           {'content': '',
                                            'link': 'http://fxn.ws/1Zlv5wG',
                                            'source': 'FoxNews',
                                            'title': '',
                                            'topic': 'gun control',
                                            'twitter': {'body': 'Obama reportedly considering executive action on gun control http://fxn.ws/1Zlv5wG via @foxnewspolitics',
                                                        'date': datetime.datetime(2015, 10, 9, 21, 1, 5),
                                                        'favs': 110,
                                                        'hashtags': '',
                                                        'id': '652695319482798083',
                                                        'link': 'https://twitter.com/FoxNews/status/652695319482798083',
                                                        'mentions': '@foxnewspolitics',
                                                        'retweets': 156}},
                                           {'content': '',
                                            'link': 'http://fxn.ws/1LFu8vg',
                                            'source': 'FoxNews',
                                            'title': '',
                                            'topic': 'gun control',
                                            'twitter': {'body': '. @GovMikeHuckabee shares his take on gun control and the liberal agenda. http://fxn.ws/1LFu8vg pic.twitter.com/OZ1oltvUqH',
                                                        'date': datetime.datetime(2015, 10, 10, 7, 27, 44),
                                                        'favs': 541,
                                                        'hashtags': '',
                                                        'id': '652853021525868544',
                                                        'link': 'https://twitter.com/FoxNews/status/652853021525868544',
                                                        'mentions': '@GovMikeHuckabee',
                                                        'retweets': 376}},
                                           {'content': '',
                                            'link': u'http://video.foxnews.com/v/444983345300',
                                            'source': 'FoxNews',
                                            'title': '',
                                            'topic': 'gun control',
                                            'twitter': {'body': u"#Guncontrol debate explodes on 'The Five' | http://video.foxnews.com/v/444983345300 1/gun-control-debate-explodes-on-the-five/ pic.twitter.com/iWPsLjwCS9",
                                                        'date': datetime.datetime(2015, 8, 29, 6, 30, 14),
                                                        'favs': 75,
                                                        'hashtags': u'#Guncontrol',
                                                        'id': '637618259806695424',
                                                        'link': 'https://twitter.com/FoxNews/status/637618259806695424',
                                                        'mentions': '',
                                                        'retweets': 74}},
                                           {'content': '',
                                            'link': u'http://fxn.ws/1JLe0kE',
                                            'source': 'FoxNews',
                                            'title': '',
                                            'topic': 'gun control',
                                            'twitter': {'body': u'Gun control groups accused of swatting open-carry permit holders http://fxn.ws/1JLe0kE via @perrych pic.twitter.com/KvIhZkesnx',
                                                        'date': datetime.datetime(2015, 9, 1, 14, 41, 5),
                                                        'favs': 85,
                                                        'hashtags': '',
                                                        'id': '638828951977103360',
                                                        'link': 'https://twitter.com/FoxNews/status/638828951977103360',
                                                        'mentions': u'@perrych',
                                                        'retweets': 172}},
                                           {'content': '',
                                            'link': 'http://fxn.ws/1JhL5UK',
                                            'source': 'FoxNews',
                                            'title': '',
                                            'topic': 'gun control',
                                            'twitter': {'body': ". @realDonaldTrump 's latest policy paper marks departure on #guncontrol http://fxn.ws/1JhL5UK @foxnewspolitics pic.twitter.com/fb1IwxFS18",
                                                        'date': datetime.datetime(2015, 9, 19, 18, 0, 14),
                                                        'favs': 186,
                                                        'hashtags': '#guncontrol',
                                                        'id': '645402049954254848',
                                                        'link': 'https://twitter.com/FoxNews/status/645402049954254848',
                                                        'mentions': '@realDonaldTrump @foxnewspolitics',
                                                        'retweets': 87}},
                                           {'content': '',
                                            'link': 'http://fxn.ws/1IrGvcL',
                                            'source': 'FoxNews',
                                            'title': '',
                                            'topic': 'gun control',
                                            'twitter': {'body': 'Obama expresses frustration over gun control debate in interview. http://fxn.ws/1IrGvcL pic.twitter.com/1tdyrq0D1P',
                                                        'date': datetime.datetime(2015, 7, 24, 11, 0, 43),
                                                        'favs': 48,
                                                        'hashtags': '',
                                                        'id': '624640369334968320',
                                                        'link': 'https://twitter.com/FoxNews/status/624640369334968320',
                                                        'mentions': '',
                                                        'retweets': 61}},
                                           {'content': '',
                                            'link': 'http://fxn.ws/1el4YT',
                                            'source': 'FoxNews',
                                            'title': '',
                                            'topic': 'gun control',
                                            'twitter': {'body': "Hours before #Layette shooting, Obama called failure of gun control legislation 'distressing' http://fxn.ws/1el4YT1",
                                                        'date': datetime.datetime(2015, 7, 23, 21, 17, 38),
                                                        'favs': 93,
                                                        'hashtags': '#Layette',
                                                        'id': '624433230373089281',
                                                        'link': 'https://twitter.com/FoxNews/status/624433230373089281',
                                                        'mentions': '',
                                                        'retweets': 98}}],
                               'cnn': [{'content': '',
                                        'link': 'http://cnn.it/1SUSgwK',
                                        'source': 'cnn',
                                        'title': '',
                                        'topic': 'gun control',
                                        'twitter': {'body': "Where is @BernieSanders ' gun control plan? http://cnn.it/1SUSgwK pic.twitter.com/nGL4jBJ4QP",
                                                    'date': datetime.datetime(2016, 2, 18, 11, 45),
                                                    'favs': 157,
                                                    'hashtags': '',
                                                    'id': '700405676628172800',
                                                    'link': 'https://twitter.com/CNN/status/700405676628172800',
                                                    'mentions': '@BernieSanders',
                                                    'retweets': 107}},
                                       {'content': '',
                                        'link': 'http://cnn.it/1SUSgwK',
                                        'source': 'cnn',
                                        'title': '',
                                        'topic': 'gun control',
                                        'twitter': {'body': "Where is @BernieSanders ' gun control plan? http://cnn.it/1SUSgwK pic.twitter.com/nGL4jBJ4QP",
                                                    'date': datetime.datetime(2016, 2, 18, 11, 45),
                                                    'favs': 157,
                                                    'hashtags': '',
                                                    'id': '700405676628172800',
                                                    'link': 'https://twitter.com/CNN/status/700405676628172800',
                                                    'mentions': '@BernieSanders',
                                                    'retweets': 107}},
                                       {'content': '',
                                        'link': 'http://cnn.it/1SUSgwK',
                                        'source': 'cnn',
                                        'title': '',
                                        'topic': 'gun control',
                                        'twitter': {'body': "Where is @BernieSanders ' gun control plan? http://cnn.it/1SUSgwK pic.twitter.com/nGL4jBJ4QP",
                                                    'date': datetime.datetime(2016, 2, 18, 11, 45),
                                                    'favs': 157,
                                                    'hashtags': '',
                                                    'id': '700405676628172800',
                                                    'link': 'https://twitter.com/CNN/status/700405676628172800',
                                                    'mentions': '@BernieSanders',
                                                    'retweets': 107}},
                                       {'content': '',
                                        'link': 'http://cnn.it/1SUSgwK',
                                        'source': 'cnn',
                                        'title': '',
                                        'topic': 'gun control',
                                        'twitter': {'body': "Where is @BernieSanders ' gun control plan? http://cnn.it/1SUSgwK pic.twitter.com/nGL4jBJ4QP",
                                                    'date': datetime.datetime(2016, 2, 18, 11, 45),
                                                    'favs': 157,
                                                    'hashtags': '',
                                                    'id': '700405676628172800',
                                                    'link': 'https://twitter.com/CNN/status/700405676628172800',
                                                    'mentions': '@BernieSanders',
                                                    'retweets': 107}},
                                       {'content': '',
                                        'link': 'http://cnn.it/1SUSgwK',
                                        'source': 'cnn',
                                        'title': '',
                                        'topic': 'gun control',
                                        'twitter': {'body': "Where is @BernieSanders ' gun control plan? http://cnn.it/1SUSgwK pic.twitter.com/nGL4jBJ4QP",
                                                    'date': datetime.datetime(2016, 2, 18, 11, 45),
                                                    'favs': 157,
                                                    'hashtags': '',
                                                    'id': '700405676628172800',
                                                    'link': 'https://twitter.com/CNN/status/700405676628172800',
                                                    'mentions': '@BernieSanders',
                                                    'retweets': 107}},
                                       {'content': '',
                                        'link': 'http://cnn.it/1ZMJMIA',
                                        'source': 'cnn',
                                        'title': '',
                                        'topic': 'gun control',
                                        'twitter': {'body': "GOP 2016 candidates bash @POTUS 's gun control push http://cnn.it/1ZMJMIA pic.twitter.com/Kiafad2QX1",
                                                    'date': datetime.datetime(2016, 1, 5, 15, 2, 1),
                                                    'favs': 233,
                                                    'hashtags': '',
                                                    'id': '684510188804673537',
                                                    'link': 'https://twitter.com/CNN/status/684510188804673537',
                                                    'mentions': '@POTUS',
                                                    'retweets': 147}},
                                       {'content': '',
                                        'link': 'http://cnn.it/1PMM87g',
                                        'source': 'cnn',
                                        'title': '',
                                        'topic': 'gun control',
                                        'twitter': {'body': "Booming gun sales may be due to @POTUS ' stance on gun control http://cnn.it/1PMM87g pic.twitter.com/czwbyHV3No",
                                                    'date': datetime.datetime(2016, 1, 6, 3, 52, 39),
                                                    'favs': 201,
                                                    'hashtags': '',
                                                    'id': '684704124911415297',
                                                    'link': 'https://twitter.com/CNN/status/684704124911415297',
                                                    'mentions': '@POTUS',
                                                    'retweets': 147}},
                                       {'content': '',
                                        'link': 'http://cnn.it/1PQhcTE',
                                        'source': 'cnn',
                                        'title': '',
                                        'topic': 'gun control',
                                        'twitter': {'body': "'American Sniper' widow, Taya Kyle, says gun control won't protect us http://cnn.it/1PQhcTE pic.twitter.com/O5fNERP9aF",
                                                    'date': datetime.datetime(2016, 1, 7, 8, 11, 52),
                                                    'favs': 573,
                                                    'hashtags': '',
                                                    'id': '685131747151986689',
                                                    'link': 'https://twitter.com/CNN/status/685131747151986689',
                                                    'mentions': '',
                                                    'retweets': 317}},
                                       {'content': '',
                                        'link': 'http://cnn.it/1TTybE0',
                                        'source': 'cnn',
                                        'title': '',
                                        'topic': 'gun control',
                                        'twitter': {'body': '. @HillaryClinton slams @BernieSanders for his stance on gun control http://cnn.it/1TTybE0 #HillaryOnCNN http://cnn.it/1Q3CVb1',
                                                    'date': datetime.datetime(2016, 1, 12, 16, 33, 39),
                                                    'favs': 137,
                                                    'hashtags': '#HillaryOnCNN',
                                                    'id': '687069965753671680',
                                                    'link': 'https://twitter.com/CNN/status/687069965753671680',
                                                    'mentions': '@HillaryClinton @BernieSanders',
                                                    'retweets': 75}},
                                       {'content': '',
                                        'link': 'http://cnn.it/1Nf0LtN',
                                        'source': 'cnn',
                                        'title': '',
                                        'topic': 'gun control',
                                        'twitter': {'body': '. @BernieSanders defends his gun control record at the #DemDebate http://cnn.it/1Nf0LtN pic.twitter.com/YiDN2nW0PH',
                                                    'date': datetime.datetime(2016, 1, 17, 19, 1, 33),
                                                    'favs': 176,
                                                    'hashtags': '#DemDebate',
                                                    'id': '688919124383256576',
                                                    'link': 'https://twitter.com/CNN/status/688919124383256576',
                                                    'mentions': '@BernieSanders',
                                                    'retweets': 70}}]}}


stories = []

for source in newsSources:
    for story in xrange(len(finalTweets['gun control'][source])):
        stories.append(finalTweets['gun control'][source][story])

print len(stories)